#!/bin/bash
#
# Copies files required to compile foocanvas into zmap from
# ./tmp_merged_foocanvas/libfoocanvas to ../src/libzmapfoocanvas.
#
# Only the Makefile.am and code files need to be copied, the configure
# files and other install files are not required because we are
# compiling libzmapfoocanvas into zmap directly as a part of our
# zmap build.
#
# The process is slightly complicated by the fact that we keep the
# files in ../src/libzmapfoocanvas in cvs as a convenience so that
# they get checked out when the user does a src checkout. This means
# the user can just go ahead and do a build of zmap without having
# to do makedirs, makepatch etc.
#
#

scriptname=`basename $0`

# error and exit routine, call with an error string as the only arg.
msgAndExit ()
{
  errmsg="$scriptname - Fatal Error: $1 !!"

  echo "$errmsg"

  exit 1
}


merged_dir='./tmp_merged_foocanvas'
code_dir="$merged_dir/libfoocanvas"
target_base='libzmapfoocanvas'
target_dir="../src/$target_base"
curr_dir=`pwd`
curr_dir=`basename $curr_dir`
base_dir='ZMap'


# currently scripts MUST be run in the Zmap/foocanvas directory or they
# won't work.
if [ $curr_dir != 'foocanvas' ]
then
  msgAndExit "Script must be run from the $base_dir/foocanvas directory !"
fi



if [ ! -d $target_dir ]
then
  msgAndExit "there is no $target_dir, please do a CVS update of $base_dir"
fi



# Need to cvs edit $target_dir files: doing cvs edit ../src/libzmapfoocanvas
# causes errors, I don't know why, hence all the cd'ing business....
#
tmp_dir=`pwd`
cd ../src
cvs edit $target_base || msgAndExit "cvs edit $target_base failed."
cd $tmp_dir

# copy the files.
echo "Copying Makefile.am from $code_dir to $target_dir"
cp -f "$code_dir/Makefile.am" $target_dir
echo "Copying all code files from $code_dir to $target_dir"
cp -f $code_dir/*.[ch] $target_dir
cp -f "$code_dir/foo-canvas-marshal.list" $target_dir
echo "done"


# Now cvs commit $target_dir files, -f flag forces the commit for
# files that have not changed.
#

tmp_dir=`pwd`
cd ../src
cvs commit -f -m "Updated files from ZMap/foocanvas." $target_base || msgAndExit "cvs commit $target_base failed."
cd $tmp_dir



exit 0




