#!/bin/bash
#
# Run the foocanvas bootstrap script, do a make to check that the
# zmap foocanvas builds and then make the distribution file for
# installing on other systems.
#
# NOTE that for the moment this script only runs on Linux (deskpro)
#
#


scriptname=`basename $0`


msgAndExit ()
{
  errmsg="$scriptname - Fatal Error: $1 !!"

  echo "$errmsg"

  exit 1
}


#
# This versioning all needs a bit of formalising so we have a version
# in one of our files and use that, I guess the package config file
# does that ?? Whatever we do it shouldn't really be hard-coded like this.
#
#today=`date +%Y-%m-%d`
#prefix="ZMap_FooCanvas_$today"
dist_file='libzmapfoocanvas-0.1.tar.gz'


merged='./tmp_merged_foocanvas'
tools_prefix='/software/acedb'
html_file='foocanvas_build.html'



opsys=`uname -s`

case $opsys in

  Linux)  opmach=`uname -m`

          case $opmach in
            i686) echo on right linux machine ;;
	       *) msgAndExit "Unsupported Linux architecture: $opmach" ;;
          esac
          ;;

  *) msgAndExit "Unsupported operating system: $opsys" ;;

esac


# Get to the right directory.
cd $merged || msgAndExit "Could not cd to $merged"


# Make sure we use tools from right place.
export PATH="$tools_prefix/bin:$PATH"
export ACLOCAL_FLAGS=" -I $tools_prefix/share/aclocal -I $tools_prefix/share/aclocal-1.9 "


# Giving a prefix here means no need to specify it for the normal install.
./autogen.sh --prefix=$tools_prefix || msgAndExit "./autogen.sh failed"

make || msgAndExit "Could not make zmap foocanvas"

make dist || msgAndExit "Could not make distribution of zmap foocanvas"

echo
echo "*** Read instructions in ./$html_file for how to use the distribution file $dist_file ***"
echo

exit 0
