/* Do not Edit - generated by makefile target build-version-file */
#include <zmapUtils_P.h>
#define ZMAP_DEVELOPMENT_ID "develop-Release_0_1_135-130-gd3642bc"
char *zmapDevelopmentString(void) { return ZMAP_DEVELOPMENT_ID ; } char *zmapCompileString(void) { return ZMAP_COMPILE_STRING() ; }                        
