#!/bin/bash

. ./zmap_proxy.sh
. ./zmap_perl.sh

#./zmap_get_bam --file=http://hgdownload-test.cse.ucsc.edu/goldenPath/hg19/encodeDCC/wgEncodeCshlLongRnaSeq/releaseLatest/wgEncodeCshlLongRnaSeqH1hescCellPapAlnRep1.bam --start=85591570 --end=87672398 --chr=chr16 --gff_feature_source=Tier1_H1-hESC_cell_longPolyA_rep1 --gff_seqname=chr16-03

./zmap_get_bam --chr=chr10 --start=31536329 --end=31721845 --file=http%3A%2F%2Fhgdownload-test.cse.ucsc.edu%2FgoldenPath%2Fhg19%2FencodeDCC%2FwgEncodeCshlLongRnaSeq%2FreleaseLatest%2FwgEncodeCshlLongRnaSeqH1hescCellPapAlnRep1.bam --gff_feature_source=Tier1_H1-hESC_cell_longPolyA_rep1 --gff_seqname=chr10-10

#/software/anacode/otter/otter_rel72/bin/bam_get_align \'--chr=chr10-10\' \'--csver=GRCh37\' \'--end=31721845\' \'--file=http%3A%2F%2Fhgdownload-test.cse.ucsc.edu%2FgoldenPath%2Fhg19%2FencodeDCC%2FwgEncodeCshlLongRnaSeq%2FreleaseLatest%2FwgEncodeCshlLongRnaSeqH1hescCellPapAlnRep1.bam\' \'--gff_feature_source=Tier1_H1-hESC_cell_longPolyA_rep1\' \'--start=31536329\' \'-gff_version=2\' \'--dataset=human\' \'--gff_seqname=chr10-10\'
