#!/bin/bash

. ./zmap_proxy.sh
. ./zmap_perl.sh

./zmap_get_bam --file=ftp://ftp.sanger.ac.uk/pub2/wormbase/STAFF/klh/accepted_hits.bam --start=1 --end=37801 --chr=CHROMOSOME_IV --gff_feature_source=accepted_hits --gff_version=3 --gff_seqname=AH6

