#!/bin/tcsh
# rebuild all pages
# must be run from ZMap/docs/Intweb directory

./scripts/docgen *.html
cd Design
../scripts/docgen *.html
cd modules
../../scripts/docgen *.html
cd ../misc
../../scripts/docgen *.html
cd ../notes
../../scripts/docgen *.html
cd ../../Development
../scripts/docgen *.html


echo "need to update this for other directories eg foocanvas"
