#!/bin/tcsh
# rebuild all pages
# must be run from ZMap/docs/Intweb directory

docgen *.html
cd Design
docgen *.html
cd modules
docgen *.html
cd ../misc
docgen *.html
cd ../notes
docgen *.html
cd ../../Development
docgen *.html


echo "need to update this for other directories eg foocanvas"
