#!/bin/sh
# make blank pages for all the modules and a couple of libraries

./new zmapApp "main program"
./new zmapConfig "configuration file handler"
./new zmapControl "user interface - main menus and buttons"
./new zmapDAS "DAS interface"
./new zmapDocs "Doxygen main page"
./new zmapDraw "mainly old code?"
./new zmapFeature "Feature Context - the model part of MVC"
./new zmapGFF "GFF file handler"
./new zmapMake "build scripts"
./new zmapManager "App/Control?"
./new zmapNavigator "the left hand navigator pane"
./new zmapNoThreads "obsolete?"
./new zmapServer "thread based external interfaces"
./new zmapThreads "thread handling ficntion used for servers"
./new zmapUtils "Miscellaneous functions"
./new zmapView "a mixture of V and C from MVC"
./new zmapWindow "the Window manager"
./new zmapWindow/items "extensions to the foo canvas"
./new zmapWindow "the display / interface to the canvas"
./new zmapXML "comms between zmap and Otterlace usign XML and X-Atoms"
./new foocanvas "third party GTK canavs widget"
./new g2 "printer format driver"






















