#
# - Copy into your own subdirectory.
# - Fill in your own macros, header, objects below.
# - You should not need to alter the final section that includes
#   the common makefile stuff.
#
#


#
# point to common make include file which contains all the rules etc.
#
ROOT_DIRECTORY = ..
MAKEDEFS_DIR = $(ROOT_DIRECTORY)/zmapMake


# local macros
PRIV_HDRS = xxxx.h
PRIV_SRC = xxx.c yyyy.c
PRIV_OBJ = xxx.o yyyy.o
PRIV_LIB = $(ZMAPAPP_LIB)
PRIV_INC = -Iany_hdrs_I_need                                                              


#
# These must all be set for the common includes to work.
#
CURRENT_INC = $(PRIV_INC)
CURRENT_LIB = $(PRIV_LIB)
CURRENT_OBJ = $(PRIV_OBJ)
CURRENT_DEP = $(PRIV_HDRS)
CURRENT_SRC = $(PRIV_HDRS) $(PRIV_SRC)


#
# include all common defines
#
include $(MAKEDEFS_DIR)/common.defs


#
# override any of the common defines that you need to here...
#


#
# include all common targets
#
include $(MAKEDEFS_DIR)/common.targets


#
# include your own targets here.
#
