#!/usr/local/bin/bash
#
# Noddy script to build aceconn package and install correct bits in to
# zmap prefix dirs, this should in the end be redundant when aceconn
# is made into an autoconf/make package.
#



msgAndExit ()
{
  echo "Error: $1"
  exit 1
}



#
# main routine
#

zmapsrcdir=~acedb/ZMap
builddir='aceconnbuild'
cvs_aceconn="Ace-Conn"

# make a build directory in our zmap subdirectory.
#
cd $zmapsrcdir || msgAndExit "Cannot cd to ZMap directory: $zmapsrcdir"

mkdir $builddir || msgAndExit "Could not make build directory: $builddir"

cd $builddir || msgAndExit "Could not cd to build directory: $builddir"


# checkout the code and build it.
#
cvs checkout $cvs_aceconn || msgAndExit "Could not checkout $cvs_aceconn from cvs."

cd $cvs_aceconn || msgAndExit "Could not cd to build directory: $cvs_aceconn"

# We need a threads build of aceconn so must reset ACEDB_MACHINE
case $ACEDB_MACHINE in

  ALPHA_* )
    target_dir='ALPHA' 
    ACEDB_MACHINE='ALPHA_5_THR'
    export ACEDB_MACHINE ;;

  LINUX_* )
    target_dir='LINUX'
    ACEDB_MACHINE='LINUX_4_THR'
    export ACEDB_MACHINE ;;

  * )
    msgAndExit "unsupported ACEDB_MACHINE type: $ACEDB_MACHINE" ;;

esac


make all bindistclean || msgAndExit "Build of $cvs_aceconn failed."


# put binaries etc. where they should be.
#
pc_file=`basename AceConn-1.1.pc.$target_dir .$target_dir`

cp -f *.pc.$target_dir $zmapsrcdir/prefix/$target_dir/lib/pkgconfig/$pc_file || msgAndExit "copy of pkgconfig files failed."

cp -f AceConn.h $zmapsrcdir/prefix/$target_dir/include || msgAndExit "copy of include failed."

mv -f bin.$ACEDB_MACHINE/*.a $zmapsrcdir/prefix/$target_dir/lib/ || msgAndExit "copy of libraries failed."

mv -f bin.$ACEDB_MACHINE/* $zmapsrcdir/prefix/$target_dir/bin || msgAndExit "copy of binaries failed."



# clear up.
#
cd $zmapsrcdir || msgAndExit "Cannot cd to ZMap directory: $zmapsrcdir"

rm -rf $builddir || msgAndExit "Could not remove build directory: $builddir"


exit 0

