#!/usr/local/bin/bash
#
# checkout, build and test acedb and put binaries in common zmap bin dirs
# for linux and alpha.
#


#
# main routine
#

# set up common functions.
if [[ -f Bfunctions && -x Bfunctions ]] ; then
  . ZBfunctions $0
else
  echo 'Cannot load ZBfunctions'
  exit 1
fi


acedb_dir=~acedb
zmap_dir=~acedb/ZMap
prefix='ZMAP_ACEDB_BUILD'
user=`whoami`
logfile="$prefix.out"

# go to acedb build dir.
#
ZBGotoDir $acedb_dir


# use the acedb build script to do the checkout/build/test
updatetree $prefix $user nostatic >$logfile 2>&1 || ZBmsgAndExit "Acedb build failed, look in: $logfile"


# Now we will need to copy stuff around to get it in the correct places...

cp -f $prefix/bin.ALPHA_5/* ZMap/prefix/ALPHA/bin || ZBmsgAndExit "Could not copy binaries in $prefix/bin.ALPHA_5/"

cp -f $prefix/bin.LINUX_4/* ZMap/prefix/LINUX/bin || ZBmsgAndExit "Could not copy binaries in $prefix/bin.LINUX_4/"

# and tidy up...
rm -rf ./$prefix ./$prefix.BUILD ./$logfile || ZBmsgAndExit "Could not erase build dirs/files"

exit 0

