#!/usr/local/bin/bash
#
# Cribbed from systems who use it to look at tickets.
#
# The rt application is in /software/bin currently.
#
#
#

RT_BIN='/software/bin/rt'


usage=" $0 <date> <list of queues>

    date is in the format dd/mm/yyyy

    queues should be a blank separated list of valid RT queues.
"


. $BASE_DIR/zmap_functions.sh || { echo "Failed to load zmap_functions.sh"; exit 1; }

set -o history

. $BASE_DIR/build_config.sh   || { echo "Failed to load build_config.sh";   exit 1; }




[ "x$start_date" != "x" ] || start_date=$1

if [ -z "$start_date" ] ; then
  zmap_message_rm_exit $usage
fi

shift

# A list of blank separated queues is allowed.
[ "x$OPS_QUEUES" != "x" ] || OPS_QUEUES="$*"
if  [ -z "$OPS_QUEUES" ] ; then
  zmap_message_rm_exit $usage
fi


zmap_message_out "Starting to fetch RT tickets for start date $start_date on queues $OPS_QUEUES"


#echo "STarting first query of RT...gets the ticket numbers"

SingleQueue () {
for QUEUE in $*
do

# a good way to work out what the params should look like is to try them out in web search interface.
#
# queries can be very complex:
#
#echo -n -e `rt-3.4 search -i  "(Queue = '$QUEUE') and  ( status='open' or status='new') and created > '-1 week'"`

echo -n -e `$RT_BIN search -i "(Queue = '$QUEUE') and  (status = 'resolved') and resolved > '$start_date'"`
echo

done
}


#echo "STarting second query of RT...displays the tickets"

#echo "Queues = $OPS_QUEUES"


for TICKET in `SingleQueue $OPS_QUEUES` 
do

#echo $TICKET

# You can add stuff to the -f flag like Created and so on.
$RT_BIN show -t ticket -f Queue,Subject,Requestors,Owner,Resolved $TICKET

echo

done

zmap_message_out "Finished fetching RT tickets."

exit 0
