#!/usr/local/bin/bash
#
# Cribbed from systems who use it to look at tickets.
#
# The rt application is currently installed in /software/acedb/bin so 
# needs to be added to the path.
#
#
#

usage=" $0 <date> <list of queues>

    date is in the format dd/mm/yyyy

    queues should be a blank separated list of valid RT queues.
"

[ "x$start_date" != "x" ] || start_date=$1

if [ -z "$start_date" ] ; then
  echo $usage
  exit 1
fi
shift

# A list of blank separated queues is allowed.
[ "x$OPS_QUEUES" != "x" ] || OPS_QUEUES="$*"
if  [ -z "$OPS_QUEUES" ] ; then
  echo $usage
  exit 1
fi


#echo "STarting first query of RT..."

SingleQueue () {
for QUEUE in $*
do

# a good way to work out what the params should look like is to try them out in web search interface.
#
# queries can be very complex:
#
#echo -n -e `rt-3.4 search -i  "(Queue = '$QUEUE') and  ( status='open' or status='new') and created > '-1 week'"`

echo -n -e `rt search -i "(Queue = '$QUEUE') and  (status = 'resolved') and resolved > '$start_date'"`
echo

done
}


#echo "STarting second query of RT..."

for TICKET in `SingleQueue $OPS_QUEUES` 
do

#echo $TICKET

# You can add stuff to the -f flag like Created and so on.
rt show -t ticket -f Queue,Subject,Requestors,Resolved $TICKET

echo

done


exit 0
