#!/bin/bash
#
# Script to update this scripts directory and optionally run a build script.
#
# NOTE that this script assumes that you want to use the build scripts
# scripts in the master copy. If you are developing different versions
# of the scripts then don't run this script !
#


# Usage: message_out Your Message
function message_out
{
    now=$(date +%H:%M:%S)
    echo "[$SCRIPT_NAME ($now)] $*"
}

# Usage: message_err Your Message
function message_err
{
    now=$(date +%H:%M:%S)
    echo "[$SCRIPT_NAME ($now)] $* !" >&2
}

# Usage: message_exit Your Message
function message_exit
{
    message_err $*
    exit 1 ;
}


RC=0
git_branch='origin'


echo

# Update this directory from git repository.
#
echo "Updating current directory from git $git_branch"
echo "==============================================="
git pull $git_branch || message_exit "git pull failed"
echo "==============================================="


# If a program was specified then get hold of it's name and args.
#
if (( $# != 0 )) ; then

  echo

  prog=$1
  shift
  args=$*


  echo "Running '$prog' with args: '$args'"
  echo "==============================================="
  eval $prog $args  ||  message_exit "$prog failed"
  echo "==============================================="

fi

echo

exit $RC
