#!/bin/bash
#
# Builds the release notes as much as is possible. Currently it does
# not seem possible to automate the Request Tracker queries that get
# the tickets that have been resolved after a certain date.
#

# How to run the script:
#
# zmapreleasenotes <last_release_date> <target_dir>
#
# e.g.
#
# 
#
#


#
# main routine
#

# set up common functions.
. ZBfunctions $0

# Setting this variable means fatal messages also get mailed to the zmap developers
# mail alias.
#
# uncomment when I've finished testing...sigh...
#
#ZBmailOnExit="true"


# set up usage strings.
cmdstring='[ -d<date> -n -z ] <target_release_notes_directory>'
descstring='
   -d   specify date from which changes/tickets should be extracted,
        date must be in form "dd/mm/yyyy" (defaults to date in ZMap/doc/Release_notes/LAST_RELEASE_DATE.txt)

   -n   DO NOT put the release notes in cvs or update the date file there

   -z   do only zmap release notes (default is to include acedb etc. as well)

   <target_release_notes_directory> 
        specifies the directory where the release notes will be built and copied to.'


build='all'

targetdir=''
builddir=$ZBReleaseBase

zmap_CVSROOT=$ZBCVSRoot
zmap_src_dir='ZMap/src'
zmap_doc_dir='ZMap/doc'
release_notes_dir="$zmap_doc_dir/Release_notes"
webpagefile="include/ZMap/zmapWebPages.h"


acedb_release_dir="$ZBAcedbHOME/RELEASE."$ZBAcedbVersion'.BUILD'

rel_template='release_notes_template.shtml'
rel_prefix='release_notes'
rel_suffix='shtml'

last_release_file="LAST_RELEASE_DATE.txt"



#
# Get the cmd line stuff...
#

while getopts ":dnz" opt ; do
  case $opt in
    d  ) prev_date=$OPTARG ;;
    n  ) no_cvs="true"     ;;
    z  ) build="zmap"      ;;
    \? ) ZBusage "$cmdstring" "$descstring" "Bad command line flag"
  esac
done
shift $(($OPTIND - 1))					    # Move on to rest of cmdline args.


# Get the target directory for the build.
if [ -z "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "No target directory specified."
fi
targetdir=$1



#
# Now we've got everything signal that the build has started.
#
ZBlogmsg "Build release notes started"



# Set up the build directory.
ZBGotoDir $targetdir
mkdir -p $builddir || ZBmsgAndExit "Cannot make build directory: $builddir"
ZBGotoDir $builddir


# check out zmap and if requested, acedb source, note, we don't need all of the zmap source stuff....
#

CVSROOT="$zmap_CVSROOT"
ZBlogmsg "Checking out from $CVSROOT"
cvs checkout $zmap_doc_dir || ZBmsgAndExit "Cannot checkout release notes directory: $zmap_doc_dir"

cvs checkout $zmap_src_dir || ZBmsgAndExit "Cannot checkout source code directory: $release_notes_dir"


if [ $build = 'all' ] ; then
    ZBlogmsg "Using Acedb Source in $acedb_release_dir rather than checking out local copy"
    #cvs export $acedb_src_dir || ZBmsgAndExit "Cannot checkout source code directory: $release_notes_dir"
fi



# Get the date to use for looking for cvs changes and RT tickets and set up
# dates for RT and cvschanges. If the user didn't specify one, we use the date
# in the cvs file LAST_RELEASE_DATE.txt in doc/Release_notes
#
if [ -z "$prev_date" ] ; then
  prev_date=`cat $release_notes_dir/$last_release_file` || ZBmsgAndExit "Cannot access date from date file $last_release_file"
fi


rt_date=$prev_date
rt_todays_date=`date "+%d/%m/%Y"`


sep=$IFS
IFS='/'
set $prev_date
prev_date="$3-$2-$1"
IFS=$sep

# Note how cvs needs tomorrows date in order to return todays changes...sigh...
tomorrows_date=`date -d"tomorrow" "+%Y-%m-%d"`
cvs_date="$prev_date<$tomorrows_date"

#echo $rt_date
#echo $cvs_date



# Set up the release notes file....
file_date=`date "+%Y_%m_%d"`
release_file="$rel_prefix.$file_date.$rel_suffix"
touch $release_file || ZBmsgAndExit "Cannot touch $release_file"
chmod u+rw $release_file || ZBmsgAndExit "Cannot make $release_file readable/writeable"


# We need a human readable date in several places in the html.
text_date=`date "+%e %B %Y"`

#
# Write the proper header for sanger pages
# oops some stuff to construct here...the date !!
#
echo '<!--#set var="banner" value="ZMap Release Notes For '$text_date'"-->' >> $release_file
echo '<!--#include virtual="/perl/header"-->' >> $release_file
echo '<!--#set var="author" value="edgrif@sanger.ac.uk" -->' >> $release_file
echo  >> $release_file



# Extract the zmap version from the code header.
#
zmap_version=`grep ZMAP_VERSION ZMap/src/zmapUtils/zmapUtils_P.h`
set $zmap_version
zmap_version=$3
zmap_release=`grep ZMAP_RELEASE ZMap/src/zmapUtils/zmapUtils_P.h`
set $zmap_release
zmap_release=$3
zmap_update=`grep ZMAP_UPDATE  ZMap/src/zmapUtils/zmapUtils_P.h`
set $zmap_update
zmap_update=$3
#echo "zmap version: $zmap_version $zmap_release $zmap_update"

zmap_version_txt="$zmap_version.$zmap_release.$zmap_update"
echo "<h3>Release Version: ZMap $zmap_version_txt</h3>" >> $release_file



echo  >> $release_file
echo "<h3>Release Date: $text_date</h3>" >> $release_file
echo  >> $release_file
echo
echo "<P>" >> $release_file
echo "(Last release was on $rt_date)" >> $release_file


echo  >> $release_file
echo "<h3>Request Tracker Tickets Resolved</h3>" >> $release_file
echo  >> $release_file


RTSERVER=scratchy

# do zmap RT tickets
#

echo  >> $release_file
echo "<h4>ZMap</h4>" >> $release_file
echo  >> $release_file

echo "<PRE>" >> $release_file

change_file='ZMap.cvschanges'

ZBlogmsg $ZBgetRTtickets $rt_date zmap
ssh $RTSERVER "$ZBgetRTtickets $rt_date zmap" > $change_file

cat $change_file | grep -v 'sysmandir' | grep -v 'Queue' >> $release_file

rm -f $change_file || ZBmsgAndExit "Cannot remove changes file: $change_file"

echo "</PRE>" >> $release_file
echo  >> $release_file


# do acedb RT tickets
#
if [ $build = 'all' ] ; then

echo  >> $release_file
echo "<h4>Acedb</h4>" >> $release_file
echo  >> $release_file

echo "<PRE>" >> $release_file

change_file='acedb.cvschanges'

ZBlogmsg $ZBgetRTtickets $rt_date acedb
ssh $RTSERVER $ZBgetRTtickets $rt_date acedb > $change_file

cat $change_file | grep -v 'sysmandir' | grep -v 'Queue' >> $release_file

rm -f $change_file || ZBmsgAndExit "Cannot remove changes file: $change_file"

echo "</PRE>" >> $release_file
echo  >> $release_file

fi


year=`date "+%Y"`					    # Used for filtering cvschanges output.

# do zmap cvs changes
#
echo  >> $release_file
echo "<h3>ZMap Changes/Fixes</h3>" >> $release_file
echo  >> $release_file

change_file='ZMAP.CHANGEFILE'
cvschanges -o$change_file -z $cvs_date ./ZMap || ZBmsgAndExit "cvschanges for zmap did not complete"
cat $change_file > /dev/null || ZBmsgAndExit "$change_file does not exist"
cat $change_file | grep -v $year | perl -lne 's/\*/<p>/; print' >> $release_file
rm -f $change_file || ZBmsgAndExit "Cannot remove change file: $change_file"
# don't remove local copy of zmap cvs yet, needed below.
echo  >> $release_file


# do acedb cvs changes
#
if [ $build = 'all' ] ; then

echo  >> $release_file
echo "<h3>Acedb Changes/Fixes</h3>" >> $release_file
echo  >> $release_file

change_file='ACEDB.CHANGEFILE'
cvschanges -o$change_file -a $cvs_date $acedb_release_dir || ZBmsgAndExit "cvschanges for acedb did not complete"
cat $change_file > /dev/null || ZBmsgAndExit "$change_file does not exist"
cat $change_file | grep -v $year | perl -lne 's/\*/<p>/; print' >> $release_file
rm -f $change_file || ZBmsgAndExit "Cannot remove change file: $change_file"
#rm -rf ./acedb || ZBmsgAndExit "Cannot remove local copy of acedb"
echo  >> $release_file

fi


#
# Add the proper html footer for sanger pages.
#
echo >> $release_file
echo '<!--#include virtual="/perl/footer"-->' >> $release_file
echo >> $release_file


#
# Optionally stick the notes in cvs and update the last release data file.....
#
if [ -z "$no_cvs" ] ; then

  ZBCVSacceptDuplicates=false

  mv -f $release_file $release_notes_dir/ || ZBmsgAndExit "Cannot move $release_file to $release_notes/"
  ZBGotoDir $release_notes_dir

  ZBsafeCVSadd $release_file
  cvs commit -m "new zmap release notes for $text_date" $release_file || ZBmsgAndExit "Cannot cvs commit $release_file in $release_notes_dir/"

  cvs edit $last_release_file || ZBmsgAndExit "Cannot cvs edit $last_release_file"
  echo $rt_todays_date > $last_release_file || ZBmsgAndExit "Cannot read date from $last_release_file"
  cvs commit -m "update last release notes to $rt_date" $last_release_file || ZBmsgAndExit "Cannot cvs commit $last_release_file"


  # Put the name of the file containing these release notes into the webpages header file
  # so the code is tied to the release notes.
  # We want to edit this line:    #define ZMAPWEB_RELEASE_NOTES "release_notes.2007_02_28.shtml"
  #

  ZBGotoDir $builddir
  ZBGotoDir $zmap_src_dir

  cvs edit $webpagefile || ZBmsgAndExit "Cannot cvs edit $webpagefile"
  perl -i -lne 's/(\#define\sZMAPWEB_RELEASE_NOTES\s)(.+)/$1"'$release_file'"/; print' $webpagefile || ZBmsgAndExit "Cannot perl edit $webpagefile"
  cvs commit -m "update release notes file to $release_file" $webpagefile || ZBmsgAndExit "Cannot cvs commit $webpagefile"
fi


# Now we can remove our local cvs copy of zmap.
rm -rf ./ZMap || ZBmsgAndExit "Cannot remove local copy of ZMap"



# Mail us to remind us to edit the release notes as there will be some editting to do...
#
ZBmsgMail "ZMap $zmap_version_txt release notes in $release_file need editting." 'Release Notes Created'


# Record end of build.
#
ZBlogmsg "Build release notes finished"


exit 0
