#!/usr/local/bin/bash
#
# This is a cover script for zmapbuild, its like this so it can run a cvs update
# to make sure the latest scripts are run to do the build.
#


#
# main routine
#

# set up common functions.
. ZBfunctions $0

# Make sure the build scripts are all in place.
zmapbootstrap  || ZBmsgAndExit "Could not update build scripts."

# do the build.
zmapbuild $@ || ZBmsgAndExit "zmapbuild failed."


exit 0

