#!/usr/local/bin/bash
#
# Update the ZMap website in wwwDev and optionally update the live website as well.
#
# Currently the script assumes the

#
# we need user to be able to specify a directory to take docs from or we should
# use a default or do a cvs checkout and use that....
#


#
# main routine
#

# set up common functions.
. ZBfunctions $0



# set up usage strings.
cmdstring='[-p] <doc_repository>'
descstring='
  -p  Publish to the live website as well

  <doc_repository> working copy of ZMap repository from which docs will be copied.'



ZBacedb='/nfs/disk100/acedb'
ZBBaseDir="$ZBacedb/ZMap"
ZBOverDir="$ZBacedb/ZMap.OVERNIGHT.BUILD"
ZBDevDir="$ZBacedb/ZMap.DEVELOPMENT.BUILD"


webpublish=''
web_site='/nfs/WWWdev/ACEDB_docs/htdocs/Development/developers_only/ZMap'
doc_dirs="web/* src/docs/ZMap/html doc"


while getopts ":p" opt ; do
  case $opt in
    p  ) webpublish='true'  ;;
    \? ) ZBusage "$cmdstring" "$descstring" "Bad command line flag"
  esac
done


# Get the source directory to be linked to.
shift $(($OPTIND - 1))
if [ -z "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "Working copy of ZMap repository must be specified."
fi
doc_rep=$1


# Make sure the website dir exists and is writeable/executable....
#
if [[ ! -d $web_site || ! -r $web_site || ! -w $web_site || ! -x $web_site ]] ; then
  ZBmsgAndExit "Development Website directory must exist and be readable/writeable/executable: $web_site"
fi


for dir in $doc_dirs
do
  this_dir="$doc_rep/$dir"

# This doesn't work because I can't get dirname to clip $dir in the way I want....
#  if [[ ! -d $this_dir || ! -r $this_dir || ! -x $this_dir ]] ; then
#    ZBmsgAndExit "Repository for website docs must exist and be readable/executable: $this_dir"
#  fi

  cp -fr $this_dir $web_site ||  ZBmsgAndExit "Could not copy $this_dir to $website"

done


# Set up docs that needs generating/copying in some way...
#
zmapdocs $web_site || ZBmsgAndExit "Processing of docs by zmapdocs script failed."



# -t is for test apparently....
if [ -n "$webpublish" ] ; then
  webpublish -t $web_site || ZBmsgAndExit "Could not copy docs to live web site."
fi


exit 0


