#!/usr/local/bin/bash
#
# Runs make on requested target (defaults to no target)
#

#
# main routine
#

# set up common functions.
. ZBfunctions $0


ZBlogmsg "ZMap make started"


# set up usage strings.
cmdstring='<make_directory>'
descstring='
   -t <target>  target for the make (defaults to no target which usually means "all").

   -b           run bootstrap script before doing the make.

   -c           run configure script before doing the make.

   <make_directory> specifies FULL PATH of directory where make is take place.'


bootstrap=""
configure=""
target=""

while getopts ":bct:" opt ; do
  case $opt in
    b  ) bootstrap='true' ;;
    c  ) configure='true' ;;
    t  ) target=$OPTARG ;;
    \? ) ZBusage "$cmdstring" "$descstring" "Bad command line flag"
  esac
done


# Get the source directory for the build.
shift $(($OPTIND - 1))
if [ -z "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "No target build directory specified."
fi
builddir=$1

# move to the build directory.
#
ZBGotoDir $builddir


# do the build.
#
if [ -n "$bootstrap" ] ; then
  ZBmsgInfo "running bootstrap"
  $builddir/runbootstrap || ZBmsgAndExit "runbootstrap script failed"
fi


if [ -n "$configure" ] ; then
  ZBmsgInfo "running configure"

  ZBExportOSVars
  echo $ZBbuildOSDir
  ZBGotoDir $ZBbuildOSDir
  $builddir/runconfig || ZBmsgAndExit "runconfig script failed"
fi


make $target || ZBmsgAndExit "make failed"


# A hack really, generalise to run a given command if you feel like it...
#
if [ -z $target ] ; then 
  $builddir/runzmap '--version' || ZBmsgAndExit "zmap would not run"
fi

ZBlogmsg "ZMap make finished"


exit 0

