#!/usr/local/bin/bash
#
# This script checks out the build scripts into our zmap scripts directory
#


#
# main routine
#

# set up common functions.
. ZBfunctions $0


# set up usage strings.
cmdstring='[-c "command"]'
descstring='
  -c "command to be run with args"   Just like the -c arg to many shells, e.g. C shell'

command=""


while getopts ":c:" opt ; do
  case $opt in
    c  ) command=$OPTARG ;;
    \? ) ZBusage "$cmdstring" "$descstring" "Bad command line flag"
  esac
done

# Check no more args
shift $(($OPTIND - 1))
if [ -n "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "Excess arguments to script."
fi


currdir=`pwd`


# move to the zmap build scripts dir and update the scripts there.
#
scriptdir=~acedb/ZMap/prefix/scripts

ZBGotoDir $scriptdir

cvs update . || ZBmsgAndExit "Cannot cvs update the build scripts"


# If there is a command, then execute it.
#
if [ -n "$command" ] ; then
    for machine in 'deskpro110' 'cbi1a' 
      do
      eval $command -m '$machine' || ZBmsgAndExit "Command failed: $command"
    done 
fi


# return to the original dir.
ZBGotoDir $currdir


exit 0

