#!/bin/bash
#
# Runs make on requested target (defaults to no target)
#

#
# main routine
#

# set up common functions.
. ZBfunctions $0


ZBlogmsg "ZMap make started"


# set up usage strings.
cmdstring='<make_directory>'
descstring='
   -t <target>  target for the make (defaults to no target which usually means "all").

   -b           run bootstrap script before doing the make.

   -c           run configure script before doing the make.

   -p <prefix>  do make install and use location when doing so.

   <make_directory> specifies FULL PATH of directory where make is take place.'


bootstrap=""
configure=""
target=""
prefix=""
perl_prefix=""

while getopts ":bct:p:" opt ; do
  case $opt in
    b  ) bootstrap='true' ;;
    c  ) configure='true' ;;
    t  ) target=$OPTARG   ;;
    p  ) prefix="--prefix=$OPTARG"; perl_prefix=$OPTARG;;
    \? ) ZBusage "$cmdstring" "$descstring" "Bad command line flag"
  esac
done

# Get the source directory for the build.
shift $(($OPTIND - 1))
if [ -z "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "No target build directory specified."
fi
builddir=$1

# move to the build directory.
#
ZBGotoDir $builddir


# do the build.
#
if [ -n "$bootstrap" ] ; then
  ZBmsgInfo "running bootstrap"
  $builddir/runbootstrap || ZBmsgAndExit "runbootstrap script failed"
fi


if [ -n "$configure" ] ; then
  ZBmsgInfo "running configure"

  ZBExportOSVars
  echo $ZBbuildOSDir
  ZBGotoDir $ZBbuildOSDir
  if [ -n "$prefix"] ; then
      $builddir/runconfig $prefix/$ZBbuildOSCanon || ZBmsgAndExit "runconfig script failed"
  else
      $builddir/runconfig || ZBmsgAndExit "runconfig script failed"
  fi
fi


make $target || ZBmsgAndExit "make $target failed in `pwd`"

if [ -n "$prefix" ] ; then

  ZBmsgInfo "running make install"
  make install || ZBmsgAndExit "make install failed in `pwd`"

  ZBmsgInfo "running X11::XRemote build and install"
  # untested. RDS
  $builddir/perl/build.sh $perl_prefix/$ZBbuildOSCanon || ZBmsgAndExit "X11::XRemote build failed"
fi


# A hack really, generalise to run a given command if you feel like it...
#
if [ -z $target ] ; then 
  $builddir/runzmap '--version' || ZBmsgAndExit "zmap would not run"
fi

ZBlogmsg "ZMap make finished"


exit 0

