#!/usr/local/bin/bash
#
# Runs entire build/checkout on various machines.
#



#
# main routine
#

# set up common functions.
. ZBfunctions $0


ZBlogmsg "ZMap build started"


# set up usage strings.
cmdstring='<target_build_directory>'
descstring='
   -v   do the build replacing target_build_directory name with ZMap.<version>.BUILD

   <target_build_directory> specifies the sub directory of ~acedb/ZMap/builds"
                            where the checkout and build should take place.'


zmaproot=~acedb/ZMap
builddir="$zmaproot/BUILDS"
zmapcvstarget='ZMap'
version=""


while getopts ":v" opt ; do
  case $opt in
    v  ) version="true"  ;;
    \? ) ZBusage "$cmdstring" "$descstring" "Bad command line flag"
  esac
done

# Get the source directory for the build.
shift $(($OPTIND - 1))
if [ -z "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "No target build directory specified."
fi
targetdir=$1


# move to the generic build directory.
#
ZBGotoDir $builddir


# remove the previous source tree and checkout the latest.
#
if [ -d $targetdir ] ; then

  rm -rf $targetdir || ZBmsgAndExit "Cannot remove contents of ZMap build directory: $targetdir"

fi

mkdir $targetdir || ZBmsgAndExit "Cannot make ZMap build directory: $targetdir"

ZBGotoDir $targetdir

cvs checkout $zmapcvstarget || ZBmsgAndExit "Cannot cvs checkout: $zmapcvstarget"


cvscopy="$builddir/$targetdir"


# do the builds on the different machines via ssh....
#
cvsbuilddir='ZMap/src'

ZBGotoDir $cvsbuilddir

abspath=`pwd`

# NOTE THAT CURRENTLY THE BUILD MUST ALL BE DONE ON THE SAME MACHINE OTHERWISE NONE
# OF THE CONFIG STUFF IS SET UP CORRECTLY....

# This will be ssh'd in the final version...on different machines....
# and we may not wish to exit, just report the failure....
# -b and -c get the bootstrap and config run, we may be able to do the bootstrap
# as a one time operation like the cvs stuff...
ssh deskpro110 "zmapmake -b -c $abspath" || ZBmsgAndExit "zmap make failed"


# making docs only works on linux at the moment as we need doxygen executables.
#
ssh deskpro110 "zmapmake -t docs $abspath" || ZBmsgAndExit "zmap make of docs failed"

docdir="$cvscopy/ZMap/doc"
ssh deskpro110 "cd $docdir ; makeQuadList TODO"


# Copy docs onto Sanger web dev site
#
zmapupdateweb "$cvscopy/ZMap"


# If release directory needs to be given a proper release name then do so...
#

if [ -n "$version" ] ; then

  ZBGotoDir $builddir

  version=`versioner -path $targetdir/ZMap/src/include/ZMap/ -show -V -quiet` || ZBmsgAndExit "Could not get zmap version"

  mv $targetdir 'ZMap.'$version'.BUILD' || ZBmsgAndExit "Could not rename build directory"
fi


ZBlogmsg "ZMap build finished"


exit 0

