#!/bin/bash

# ================= README ==================

# This is a  development version of zmap_overnight.sh that  can be run
# to  test the  build. There's  no cvs  updating to  worry  about, nor
# emailing...

# It does build the documentation,  so is slower. No other config from
# build_config.sh is altered either so will run like zmap_overnight.sh
# does.

# Output will be in RELEASE_LOCATION= directory. N.B. ~ == ~zmap

# We set the ZMAP_MASTER_BUILD_DEVELOPMENT_DIR


# ================== CONFIG ================== 
# Configuring variables
SRC_MACHINE=tviewsrv
# For development make sure these are set
CVS_CHECKOUT_SCRIPT=./build_bootstrap.sh

HOSTNAME=$(hostname)
cd $(dirname $0)
SCRIPT_DIR=$(pwd)


(cat <<EOF
#!/bin/echo Generated by $0 
echo Development script, Not for production!

ZMAP_MASTER_BUILD_DEVELOPMENT_DIR=$HOSTNAME:$SCRIPT_DIR

EOF
) | ssh $SRC_MACHINE '/bin/bash -c "cat - > /var/tmp/root_develop.sh"'

# ================== MAIN PART ================== 
# A one step copy, run, cleanup!
# The /bin/kill -9 -$$; line is there to make sure no processes are left behind if the
# root_checkout.sh looses one... In testing, but appears kill returns non-zero in $?
# actually it's probably the bash process returning the non-zero, but the next test
# appears to succeed if we enter _rm_exit(), which is what we want. 
echo "Enter zmap password at prompt."

cat $CVS_CHECKOUT_SCRIPT | ssh zmap@$SRC_MACHINE '/bin/bash -c "\
function _rm_exit                       \
{                                       \
   echo Master Script Failed...;        \
   rm -f root_checkout.sh;              \
   /bin/kill -9 -$$;                    \
   exit 1;                              \
};                                      \
cd /var/tmp                || exit 1;   \
rm -f root_checkout.sh     || exit 1;   \
cat - > root_checkout.sh   || exit 1;   \
chmod 755 root_checkout.sh || _rm_exit; \
: Change the variables in next line             ; \
./root_checkout.sh RELEASE_LOCATION=~/BUILDS/OVERNIGHT ZMAP_MASTER_RT_TO_CVS=no || _rm_exit; \
:                                               ; \
rm -f root_checkout.sh     || exit 1;   \
"' 2>&1

ssh $SRC_MACHINE 'rm -f /var/tmp/root_develop.sh'

# ================== END OF SCRIPT ================== 
