#!/usr/local/bin/bash
#
# Check out the zmap source and copy scripts to where they need to be for
# the build to run
#


#
# main routine
#

# set up common functions.
. ./ZBfunctions $0

# set up usage strings.
cmdstring='<target_build_directory>'
descstring='
         <target_build_directory> specifies the sub directory of ~acedb/ZMap/builds"
                                  where the checkout and build should take place.'


zmaproot=~acedb/ZMap
builddir="$zmaproot/builds"
zmapcvstarget='ZMap'

if [ -z "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "No target build directory specified."
fi

targetdir=$1


# move to the generic buld directory.
#
ZBGotoDir $builddir

# remove the previous source tree and checkout the latest.
#
if [ -d $targetdir ] ; then

  rm -rf $targetdir || ZBmsgAndExit "Cannot remove contents of ZMap build directory: $targetdir"

fi

mkdir $targetdir || ZBmsgAndExit "Cannot make ZMap build directory: $targetdir"

ZBGotoDir $targetdir

cvs checkout $zmapcvstarget || ZBmsgAndExit "Cannot cvs checkout: $zmapcvstarget"



# do the build.
#
cvsbuilddir='ZMap/src'

ZBGotoDir $cvsbuilddir

runbootstrap || ZBmsgAndExit "runbootstrap script failed"

runconfig || ZBmsgAndExit "runconfig script failed"

make || ZBmsgAndExit "make failed"

runzmap '--version' || ZBmsgAndExit "zmap would not run"


exit 0

