#!/usr/local/bin/bash
#
# Check out the zmap source and copy scripts to where they need to be for
# the build to run
#


#
# main routine
#

# set up common functions.
. ZBfunctions $0

# set up usage strings.
cmdstring='<target_build_directory>'
descstring='
   -v   do the build replacing target_build_directory name with ZMap.<version>.BUILD

   <target_build_directory> specifies the sub directory of ~acedb/ZMap/builds"
                            where the checkout and build should take place.'


zmaproot=~acedb/ZMap
builddir="$zmaproot/builds"
zmapcvstarget='ZMap'
version=""

while getopts ":v" opt ; do
  case $opt in
    v  ) version="true"  ;;
    \? ) ZBusage "$cmdstring" "$descstring" "Bad command line flag"
  esac
done

# Get the source directory for the build.
shift $(($OPTIND - 1))
if [ -z "$1" ] ; then
  ZBusage "$cmdstring" "$descstring" "No target build directory specified."
fi
targetdir=$1


# move to the generic build directory.
#
ZBGotoDir $builddir


# remove the previous source tree and checkout the latest.
#
if [ -d $targetdir ] ; then

  rm -rf $targetdir || ZBmsgAndExit "Cannot remove contents of ZMap build directory: $targetdir"

fi

mkdir $targetdir || ZBmsgAndExit "Cannot make ZMap build directory: $targetdir"

ZBGotoDir $targetdir

cvs checkout $zmapcvstarget || ZBmsgAndExit "Cannot cvs checkout: $zmapcvstarget"



# do the build.
#
cvsbuilddir='ZMap/src'

ZBGotoDir $cvsbuilddir

runbootstrap || ZBmsgAndExit "runbootstrap script failed"

runconfig || ZBmsgAndExit "runconfig script failed"

make || ZBmsgAndExit "make failed"

runzmap '--version' || ZBmsgAndExit "zmap would not run"


# If release directory needs to be given a proper release name then do so...
#

if [ -n "$version" ] ; then

  ZBGotoDir $builddir

  version=`versioner -path $targetdir/ZMap/src/include/ZMap/ -show -V -quiet` || ZBmsgAndExit "Could not get zmap version"

  mv $targetdir 'ZMap.'$version'.BUILD' || ZBmsgAndExit "Could not rename build directory"
fi




exit 0

