#! /bin/sh
############################################################
############################################################
# simple script bootstrap and create the configure script
# run this when changing any of the following:
#    configure.ac
#    Makefile.am
#    Makefile.in
############################################################
############################################################


############################################################
############################################################
# functions
# get_var_or_default ENVIRONMENT_VARIABLE DEFAULT_VALUE
get_var_or_default(){
    env_var=$1
    default=$2
    is_set=`eval echo "\\$$env_var"`
    if [ -z "$is_set" ]; then
        eval "$env_var=$default"
    fi
    now_set=`eval echo "\\$$env_var"`
    echo "Using ${env_var}='${now_set}'" 2>&1
}

############################################################
############################################################
# Setup
get_var_or_default ACLOCAL aclocal
get_var_or_default ACLOCAL_FLAGS
get_var_or_default AUTOHEADER autoheader
get_var_or_default AUTOMAKE automake
get_var_or_default AUTOCONF autoconf
# default to include current directory as we use ac_path_lib.m4
# I did fix it up to work with current autoconf and stop it
# complaining about deprecated macros
DEFAULT_INC="-I ."
############################################################
############################################################


############################################################
############################################################

# clean up first
# xargs: I've removed the -r because not all platforms have it.
# rm: I've added -r to deal with directories and taken away the -f so we can see any errors.
# I've changed from just cat'ing the root dir .cvsignore to all of them and then grep'ing them
# replacing .cvsignore: in the output from grep and removing the file! Ha ha.
#cat .cvsignore | xargs -t rm -r
find ./ -name '.cvsignore' | xargs grep '.' | sed -e 's/.cvsignore://' | xargs -t rm -r

# Run the autoprogs
echo "Running ${ACLOCAL}..."
${ACLOCAL} ${DEFAULT_INC}    || { echo "${ACLOCAL} failed";    exit 1; }
echo "Running ${AUTOHEADER}..."
${AUTOHEADER} --warnings=all || { echo "${AUTOHEADER} failed"; exit 1; }
echo "Running ${AUTOMAKE}..."
${AUTOMAKE} --warnings=all --gnu --add-missing --copy \
    || { echo "${AUTOMAKE} failed"; exit 1; }
echo "Running ${AUTOCONF}..."
${AUTOCONF} --warnings=all   || { echo "${AUTOCONF} failed";   exit 1; }
