#!/bin/bash
############################################################
############################################################
# simple script bootstrap and create the configure script
# run this when changing any of the following:
#    configure.ac
#    Makefile.am
#    Makefile.in
############################################################
############################################################
SCRIPT_NAME=$(basename $0)
INITIAL_DIR=$(pwd)
 SCRIPT_DIR=$(dirname $0)
if ! echo $SCRIPT_DIR | egrep -q "(^)/" ; then
   BASE_DIR=$INITIAL_DIR/$SCRIPT_DIR
else
   BASE_DIR=$SCRIPT_DIR
fi

. $BASE_DIR/../scripts/zmap_functions.sh || { echo "Failed to load zmap_functions.sh"; exit 1; }
set -o history
. $BASE_DIR/../scripts/build_config.sh   || { echo "Failed to load build_config.sh";   exit 1; }

zmap_message_out "Start of script."

############################################################
############################################################
# Setup
[ "x$LIBTOOLIZE" != "x" ]  || LIBTOOLIZE=libtoolize
[ "x$AUTOHEADER" != "x" ]  || AUTOHEADER=autoheader
[ "x$ACLOCAL" != "x" ]     || ACLOCAL=aclocal
[ "x$AUTOMAKE" != "x" ]    || AUTOMAKE=automake
[ "x$AUTOCONF" != "x" ]    || AUTOCONF=autoconf
[ "x$AUTOUPDATE" != "x" ]  || AUTOUPDATE=autoupdate

# default to include current directory as we use ac_path_lib.m4
# I did fix it up to work with current autoconf and stop it
# complaining about deprecated macros
DEFAULT_INC="-I . $ACLOCAL_FLAGS"
############################################################
############################################################


# set up zmap version number, this is arcane and horrible and all
# autoconf's fault. See http://sources.redhat.com/automake/automake.html#Rebuilding
# and the stuff about AC_INIT
# NOTE that zmap_version.m4 is referenced from configure.ac
#
version_macro_file='zmap_version.m4'
rm -f $version_macro_file
ZMAP_VERSION=`../scripts/versioner -V -path ../ -quiet`
echo "m4_define([ZMAP_VERSION_NUMBER], [$ZMAP_VERSION])" > $version_macro_file
zmap_message_out "ZMap version is: $ZMAP_VERSION"


############################################################
############################################################

# clean up first
# xargs: I've removed the -r because not all platforms have it.
# rm: I've added -r to deal with directories and taken away the -f so we can see any errors.
# I've changed from just cat'ing the root dir .cvsignore to all of them and then grep'ing them
# replacing .cvsignore: in the output from grep and removing the file! Ha ha.
#cat .cvsignore | xargs -t rm -r
find . -name '.cvsignore' | \
xargs grep '.' | \
sed -e 's/.cvsignore://' | \
while read file; do [ ! -f "$file" ] || rm -r $file; done


zmap_message_out "Running $(which $AUTOUPDATE)"
$AUTOUPDATE                  || zmap_message_exit "Failed running $AUTOUPDATE"
zmap_message_out "Running $(which $ACLOCAL) $DEFAULT_INC"
$ACLOCAL $DEFAULT_INC        || zmap_message_exit "Failed running $ACLOCAL (first time) export ACLOCAL_FLAGS='-I /<gtkprefix>/share/aclocal'"
zmap_message_out "Running $(which $AUTOHEADER)"
$AUTOHEADER --warnings=all   || zmap_message_exit "Failed running $AUTOHEADER"

if [ "x$NEED_LIBTOOLIZE" == "x$ZMAP_TRUE" ]; then 
  zmap_message_out "Running $(which $LIBTOOLIZE)"
  $LIBTOOLIZE --force --copy || zmap_message_exit "Failed running $LIBTOOLIZE"
  zmap_message_out "Running $(which $ACLOCAL) (again)"
  $ACLOCAL $DEFAULT_INC      || zmap_message_exit "Failed running $ACLOCAL (second time) export ACLOCAL_FLAGS='-I /<gtkprefix>/share/aclocal'"
fi

zmap_message_out "Running $(which $AUTOMAKE)"
$AUTOMAKE --gnu     \
    --add-missing   \
    --copy                   || zmap_message_exit "Failed running $AUTOMAKE"
zmap_message_out "Running $(which $AUTOCONF)"
$AUTOCONF --warnings=all     || zmap_message_exit "Failed running $AUTOCONF"
