#
# Common defines for zmap only.
#
# THIS IS THE WRONG WAY TO DO THIS SO WE SHOULD GET RID OF THIS
# FILE.....SOMETHING TO BE CLEANED UP AFTER THE FILE RENAME...
#


include $(top_srcdir)/Makefile.common


