
AUTOMAKE_OPTIONS = gnu

NULL = 

ARFLAGS = cru

# including ALPHA_POPT here is really bad FIND BETTER method
AM_CPPFLAGS = -g -I$(top_srcdir)/include \
	-I$(top_builddir) \
        @ALPHA_POPT@ \
	@GTK_CFLAGS@ \
	@ACECONN_CFLAGS@ \
        @LIBCURL_CPPFLAGS@ \
        $(NULL)

INCLUDE_COMMON = -I$(top_srcdir) -I$(top_srcdir)/include -I.

# Required by the install-zmap-static-libs target.
LIBS_ZMAP = $(top_builddir)/.libs/libZMapApp.a \
	$(top_builddir)/.libs/libZMapApp.la \
	$(top_builddir)/.libs/libZMap.a \
	$(top_builddir)/.libs/libZMap.la \
	$(top_builddir)/.libs/libZMapThr.a \
	$(top_builddir)/.libs/libZMapThr.la \
	$(top_builddir)/.libs/libZMapXML.a \
	$(top_builddir)/.libs/libZMapXML.la \
	$(top_builddir)/.libs/libZMapAppServices.a \
	$(top_builddir)/.libs/libZMapAppServices.la \
	$(top_builddir)/.libs/libZMapUtils.a \
	$(top_builddir)/.libs/libZMapUtils.la \
	$(top_builddir)/.libs/libzmapfoocanvas.a \
	$(top_builddir)/.libs/libzmapfoocanvas.la \
	$(top_builddir)/.libs/libPFetch.a \
	$(top_builddir)/.libs/libPFetch.la \
	$(NULL)

