
AUTOMAKE_OPTIONS = gnu

NULL = 

ARFLAGS = cru

# in the below why don't we use the "+=" syntax  for ensembl stuff too ?

# I'm hacking in zmapApp here for now....
AM_CPPFLAGS = \
-I$(top_srcdir)/zmapApp \
-I$(top_srcdir)/include \
-I$(top_builddir) \
-I$(top_srcdir)/zeromq/include \
-I$(top_srcdir) \
@GTK_CFLAGS@ \
@LIBCURL_CPPFLAGS@ \
$(NULL)

AM_CXXFLAGS = -std=c++0x -g -Wall

AM_LDFLAGS = -g -Wall


INCLUDE_COMMON = -I$(top_srcdir) -I$(top_srcdir)/include -I.

if USE_GBTOOLS
AM_CPPFLAGS += -I$(top_srcdir)/gbtools/src/include
endif

if USE_HTSLIB
AM_CPPFLAGS += -I$(top_srcdir)/htslib
endif


if USE_ACECONN
AM_CPPFLAGS += -I$(top_srcdir)/AceConn/include
endif

if USE_ENSEMBL
if USE_ENSEMBL_SUBDIR
AM_CPPFLAGS += -I$(top_srcdir)/ensc-core/src/DataModel \
-I$(top_srcdir)/ensc-core/src/DataAdaptors \
-I$(top_srcdir)/ensc-core/src/Util \
-I$(top_srcdir)/ensc-core/src/DataModel/Mapper \
-I$(top_srcdir)/ensc-core/src/DataModel/Basic \
-I$(top_srcdir)/ensc-core/src/Compara/DataAdaptors \
-I$(top_srcdir)/ensc-core/src/Compara/DataModel \
-I$(top_srcdir)/ensc-core/src/OBDA 
endif
endif



# DO WE NEED THIS ANY MORE ????
#
# Required by the install-zmap-static-libs target.
LIBS_ZMAP = $(top_builddir)/.libs/libZMapApp.a \
	$(top_builddir)/.libs/libZMapApp.la \
	$(top_builddir)/.libs/libZMap.a \
	$(top_builddir)/.libs/libZMap.la \
	$(top_builddir)/.libs/libZMapThr.a \
	$(top_builddir)/.libs/libZMapThr.la \
	$(top_builddir)/.libs/libZMapRemoteControl.a \
	$(top_builddir)/.libs/libZMapRemoteControl.la \
	$(top_builddir)/.libs/libZMapXML.a \
	$(top_builddir)/.libs/libZMapXML.la \
	$(top_builddir)/.libs/libZMapAppServices.a \
	$(top_builddir)/.libs/libZMapAppServices.la \
	$(top_builddir)/.libs/libZMapUtils.a \
	$(top_builddir)/.libs/libZMapUtils.la \
	$(top_builddir)/.libs/libzmapfoocanvas.a \
	$(top_builddir)/.libs/libzmapfoocanvas.la \
	$(NULL)

