
AUTOMAKE_OPTIONS = gnu

NULL = 

ARFLAGS = cru

# including ALPHA_POPT here is really bad FIND BETTER method
AM_CPPFLAGS = -g -I$(top_srcdir)/include \
	-I$(top_builddir) \
        @ALPHA_POPT@ \
	@GTK_CFLAGS@ \
	@FOOCANVAS_CFLAGS@ \
	@ACECONN_CFLAGS@ \
        @LIBCURL_CPPFLAGS@ \
        $(NULL)

LIBS_ZMAP = $(top_builddir)/lib/libZMapApp.a \
	$(top_builddir)/lib/libZMap.a \
	$(top_builddir)/lib/libZMapThr.a \
        $(top_builddir)/lib/libZMapXML.a \
	$(NULL)

