#!/bin/bash
#
# Noddy script to run bootstrap as alphas need a lot of help.
#



msgAndExit ()
{
  echo "Error: $1"
  exit 1
}


opsys=`uname`

case $opsys in

  OSF1 )
    locals=~zmap/prefix/ALPHA/bin
    PATH="$locals:$PATH"
    export PATH ;;

  Linux )

    case `uname -m` in
      
      x86_64 )
         locals=~zmap/prefix/LINUX_64/bin
         PATH="$locals:$PATH"
         export PATH ;;

       * )
         locals=~zmap/prefix/LINUX/bin
         PATH="$locals:$PATH"
         export PATH ;;

    esac ;;

  Darwin )

    export ACLOCAL_FLAGS=" -I /opt/local/share/aclocal"

    # This is for our Mac laptop....
    locals=/Users/edgrif/install/bin
    PATH="$locals:$PATH"
    export PATH ;;

  * )
    msgAndExit "unsupported operating system: $opsys" ;;

esac

./bootstrap || msgAndExit "bootstrap script failed"


exit 0
