#!/usr/local/bin/bash
#
# Noddy script to run bootstrap as alphas need a lot of help.
#



msgAndExit ()
{
  echo "Error: $1"
  exit 1
}


opsys=`uname`

case $opsys in

  OSF1 )
    locals=~acedb/ZMap/prefix/ALPHA/bin
    PATH="$locals:$PATH"
    export PATH ;;

  Linux )
    locals=~acedb/ZMap/prefix/LINUX/bin
    PATH="$locals:$PATH"
    export PATH ;;

  Darwin )
    # This is for our Mac laptop....
    locals=/Users/edgrif/install/bin
    PATH="$locals:$PATH"
    export PATH ;;

  * )
    msgAndExit "unsupported operating system: $opsys" ;;

esac


./bootstrap || msgAndExit "bootstrap script failed"


exit 0
