#!/usr/local/bin/bash
#
# Noddy script to run configure as alphas + Roys machine are far from standard.
#

msgAndExit ()
{
  echo "Error: $1"
  exit 1
}


opsys=`uname`

case $opsys in

  OSF1 )
    locals=~acedb/ZMap/prefix/ALPHA/bin
    PATH="$locals:/usr/local/gtk2/bin:$PATH"
    export PATH

    # NOTE that currently the LDFLAGS stuff does not get through the configure step
    # and so does not work....not sure why....
    popt=~acedb/ZMap/prefix/ALPHA
    cc_args='CC=cc'
    cflags_args="CFLAGS=-I$popt/include -msg_enable level4"
    ld_args="LDFLAGS=-rpath /usr/local/gtk2/lib:$popt/lib"

    locals=~acedb/ZMap/prefix/ALPHA/lib/pkgconfig
    PKG_CONFIG_PATH="$locals:/usr/local/gtk2/lib/pkgconfig"
    export PKG_CONFIG_PATH ;;

  Linux )
    locals=~acedb/ZMap/prefix/LINUX
    PATH="$locals/bin:$PATH"
    export PATH

    PKG_CONFIG_PATH="$locals/lib/pkgconfig"
    export PKG_CONFIG_PATH
    LD_LIBRARY_PATH=/usr/local/oracle/lib
    export LD_LIBRARY_PATH

    cc_args='CXXFLAGS=-g CFLAGS=-g'
    cflags_args=''
    ld_args='' ;;

  * )
    msgAndExit "unsupported operating system: $opsys" ;;

esac


# run the configure.......watch out for the quoting, sometimes we want the variable to
# be interpreted as a single cmdline arg, sometimes as multiple ones.
./configure $cc_args "$cflags_args" "$ld_args"


exit 0
