#!/usr/local/bin/bash
#
# Noddy script to run zmap because you need the LD_LIBRARY_PATH set on alphas.
#

msgAndExit ()
{
  echo "Error: $1"
  exit 1
}


opsys=`uname`

case $opsys in

  OSF1 )
    locals=~acedb/ZMap/prefix/ALPHA/lib
    LD_LIBRARY_PATH="$locals:/usr/local/gtk2/lib"
    export LD_LIBRARY_PATH ;;

  Linux )
    ;;

  * )
    msgAndExit "unsupported operating system: $opsys" ;;

esac


./zmap $*


exit 0
