#!/bin/tcsh
# rebuild all pages
# must be run from ZMap/doc directory

docgen *.html
cd Design_notes
docgen *.html
cd modules
docgen *.html
cd ../misc
docgen *.html
cd ../notes
docgen *.html

echo "need to update this for other directories eg foocanvas"
