#!/bin/sh
# generate a blank-ish html file
echo "<h2>" $1 - $2 "</h2>" > $1.html
echo "<fieldset> <legend>Summary</legend>" >>$1.html
echo "Forthcoming..."  >>$1.html
echo "</fieldset>" >>$1.html

docgen $1

echo now update scripts/navbar.rel and design/index.html